### ISSUE TITLE
Should anyWord16 / anyWord32 / anyWord fail when input is too short?

### ISSUE THREAD

**Issue by cdsmith** [AndrasKovacs/flatparse#15]
It looks like `anyWord16`, `anyWord32`, and `anyWord` will succeed when there are too few bytes in the buffer.  I may be missing something here, but it looks like the buffer is read past the end in this case.  Is this a bug?

Uncovered while writing test cases.

**Comment by AndrasKovacs** [comment]
It's absolutely a bug, thanks for noticing. Fixed it.

**Comment by cdsmith** [comment]
Thanks!
