### ISSUE TITLE
Provide explicit-endianness machine integer parsers

### ISSUE THREAD

**Issue by raehik** [AndrasKovacs/flatparse#18]
I'm currently parsing bytestrings with cereal. Most of my needs are simple, like reading X bytes and parsing machine integers. I found flatparse while looking for a faster library, but I see it doesn't have any parsers for machine integers with explicit endianness.

The reasoning is given in the readme, since getting good performance is harder if you have to worry about endianness. Regardless, would you consider adding explicit-endianness machine integer parsers e.g. `anyWord16le :: Parser e Word16`? I would have a go via bytewise operations on bytestrings (not all that fast, but it's how cereal implements it).

**Comment by raehik** [comment]
Thanks for the help. I think just the former. The actual endianness of the underlying machine doesn't matter, just parsing bytes as big-endian or little-endian machine integers (instead than using the host's encoding).

This works, maybe:

```haskell
-- adapted from 'anyWord16'
anyWord16le :: Parser e Word16
anyWord16le = Parser \_fp eob buf -> case 2# <=# minusAddr# eob buf of
  0# -> Fail#
  _  -> case indexWord16OffAddr# buf 0# of
    w# ->
#if defined(WORDS_BIGENDIAN)
      let w'# = byteSwap16'# w#
#else
      let w'# = w#
#endif
      in  OK# (W16# w'#) (plusAddr# buf 2#)

-- 'byteSwap16#' works on 'Word#'s, so wrapper for 'Word16#'s
byteSwap16'# :: Word16# -> Word16#
byteSwap16'# w# = wordToWord16# (byteSwap16# (word16ToWord# w#))
```

If we assume the host is little-endian, we don't need the CPP. I have no idea if `WORDS_BIGENDIAN` is even used (it shows up in GHC in a few places, so I assumed).

**Comment by raehik** [comment]
I'd also like to add some primitives like `take :: Int -> Parser e ByteString`, `getRemaining :: Parser e ByteString`. I'll gladly prepare a separate PR, but I'm aware that they probably have efficient implementations I haven't figured out.

**Comment by AndrasKovacs** [comment]
I'd appreciate the PR, you can add primitives as you like. This week I'm busy, sometimes next week I'll try to merge it.

**Comment by AndrasKovacs** [comment]
Sure, it's the way forward, but compatibility should be preserved. There's already a bunch of CPP in Flatparse.Internal for ignoring native Word#-s in GHC 9; that was my lazy solution, the proper solution is to add more CPP to support native Word#-s.

**Comment by raehik** [comment]
Roger! I get it now, I'm still new to unboxed data and was fuzzy on how to approach it. I have a changeset that refactors the CPP so we use natives in 9.2, regular `Word#`s in pre-9.2 (at least usually/by default).
