### ISSUE TITLE
flatparse is slower than bytesmith, bets @chessai

### ISSUE THREAD

**Issue by sjakobi** [AndrasKovacs/flatparse#3]
Quoting from https://functionalprogramming.slack.com/archives/C0433UN0M/p1615839832068800:

```
sjakobi: András Kovács has uploaded flatparse to Hackage! http://hackage.haskell.org/package/flatparse-0.1.0.0
chessai: Willing to bet money it's still slower than bytesmith
...
sjakobi: BTW, how much money, and can I quote you on the flatparse issue tracker? :wink:
chessai: 100 USD, you can quote me
chessai: If I am right, then I will do nothing
chessai: If I am wrong, then I will just improve bytesmith
chessai: I'm not actually convinced flatparse is slower, I just think a bet makes this interesting
```

(CC @chessai)

**Comment by AndrasKovacs** [comment]
Added [bytesmith benchmark](https://github.com/AndrasKovacs/flatparse/blob/88506ba9a3be347cc49c0ad127119bae01def856/bench/Bench.hs). So far it's slower than flatparse. I included results with `-fllvm` from my machine in the README. You can also look at CI benchmark results which are without `-fllvm`. The gap narrows for s-expressions without `-fllvm` but not really for other benchmarks.
