### ISSUE TITLE
Parse bytestring builder (return "write bytes to given address" IO action)

### ISSUE THREAD

**Issue by raehik** [AndrasKovacs/flatparse#39]
I have found a use case (i.e. it seems to be a fairly sensible type class instance somewhere) for parsing to a primitive bytestring builder. It would allow parse->serialize steps to be performed with zero intermediate copying. Perhaps you parse and edit some record, only editing select fields, and you figure the extra intermediate bytestrings (which would be copied from the parse input into their own bytestrings, then copied from again when serializing) are a waste of cycles.

I'm currently thinking of something like this (messy):

```haskell
-- for a memcpy FFI, but could (should?) redefine
import qualified Data.ByteString.Internal as B

-- returns build action and length
-- can be wrapped into any bytestring builder
takeRestPrim :: ParserT st e (Addr# -> IO (), Int)
takeRestPrim = ParserT \fp eob s st ->
  let n# = minusAddr# eob s
  in  OK# st (\sTo -> memcpy sTo s n#, I# n#) eob
{-# inline takeRestPrim #-}

memcpy :: Addr# -> Addr# -> Int# -> IO ()
memcpy sFrom sTo len# = B.memcpy (Ptr sFrom) (Ptr sTo) (fromIntegral (I# len#))

-- ... and such for the other bytestring parsers like `take`
```

Might something like this be sensible to add?

**Comment by AndrasKovacs** [comment]
This `takeRestPrim` is not memory safe because it saves an `Addr#` in a closure whose underlying data can get garbage collected subsequently. If we save a `ForeignPtr` instead, that means that the builder closure saves exactly the same data that is returned by `takeRest`. I don't see why returning a closure would be preferred.

**Comment by AndrasKovacs** [comment]
A `ByteString` has a foreign `malloc`-d array which lives while its `ForeignPtrContents` lives. Only the whole array can be freed. This implies that any slice of a `ByteString` keeps the whole original `ByteString` alive. The `touch#` and `keepAlive#` primops from `GHC.Prim` can be used to ensure that GHC doesn't transform the code in a way which causes premature death of an object. 

We use `touch#` in [`bytestring`](https://github.com/AndrasKovacs/flatparse/blob/main/src/FlatParse/Basic.hs#L295) to make sure that the backing data lives until its processing is finished. The `unsafeUseAsCString` in `runParser` also uses `touch#` or `keepAlive#` in the source.

**Comment by raehik** [comment]
Thanks a bunch for the explanation. Does that mean `takeUnsafe#`

```haskell
takeUnsafe# :: Int# -> ParserT st e B.ByteString
takeUnsafe# n# = ParserT \fp eob s st ->
    case n# <=# minusAddr# eob s of
      1# -> OK#   st (B.PS (ForeignPtr s fp) 0 (I# n#)) (plusAddr# s n#)
      _  -> Fail# st
```

keeps the input bytestring alive? Is this a good idea? Should we also provide copying parsers?

**Comment by AndrasKovacs** [comment]
[`Data.ByteString.copy`](https://hackage.haskell.org/package/bytestring-0.11.4.0/docs/Data-ByteString.html#g:24) already exists for this purpose.

**Comment by raehik** [comment]
I see. Thanks for all this. Might I document that these functions will keep the input bytestring alive? I find it unintuitive (and I worry it could lead to unexpected memory usage for some cases?)

**Comment by AndrasKovacs** [comment]
Sure.
