### ISSUE TITLE
`posLineCols` fails for more than one `Pos`

### ISSUE THREAD

**Issue by TheMatten** [AndrasKovacs/flatparse#40]
`posLineCols` fails with
```
*** Exception: FlatParse.Basic.posLineCols: invalid position
```
on any input with more than one `Pos` - problem seems to be with initial sorting assuming increasing, not decreasing values of `Pos`:
https://github.com/AndrasKovacs/flatparse/blob/702a2093d8d5171a9faee495cb0ff43878a37b5a/src/FlatParse/Basic.hs#L407

Instead, it should probably sort the opposite way, e.g. with `Down`:
```hs
sorted = sortOn (Down . snd) (zip [0..] poss)
```
and such modified function seems to work fine on some test inputs.

**Comment by AndrasKovacs** [comment]
Fixed by ba96008d900935ab118710eb7ee89dffff9949c9. I also updated on Hackage.
