### ISSUE TITLE
`Ord` instance of `Pos`

### ISSUE THREAD

**Issue by pedrominicz** [AndrasKovacs/flatparse#42]
The instance `Ord Pos` is compares positions as if they were integers, but positions get smaller further into the string! This quirk causes [`FlatParse.Examples.BasicLambda.Lexer.merge`](https://github.com/AndrasKovacs/flatparse/blob/1018d296eeb5430757a5542f08edcfc5bd9a931f/src/FlatParse/Examples/BasicLambda/Lexer.hs#L49) to prioritize "outer" errors instead of "inner" ones. The same happens [here](https://github.com/AndrasKovacs/smalltt/blob/945e04b62dc06124b867f635e2f024ed5382c0fa/src/Lexer.hs#L36).

I am not sure if it is better to change the `Ord` instance or just change the example.

**Comment by AndrasKovacs** [comment]
Thanks. The error merging was indeed just buggy. I flipped the `Ord` instance, that's the direction that really makes sense. Issue #40 also happened because of me mixing up the `Ord` direction. Addressed by eb98fcc0bff0c2aecd17a392b95ec2a87603736d. I updated the hackage version as well.
